In [5]:
def detect_face(img): 
  offset = 5
  gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

  faces = face_cascade.detectMultiScale(gray, 1.3, 5)
  return faces 

def detect_eye(gray_img):
  eyes = eye_cascade.detectMultiScale(gray_img, 1.3, 5)
  return eyes

  

In [6]:
!pip install imutils

In [38]:
import numpy as np
import cv2
import numpy as np

#import cv2.imshow as cv2_imshow

from matplotlib import pyplot as plt

# initialize the Haar Cascade face detection model 
#face_cascade = cv2.CascadeClassifier('/content/drive/MyDrive/Etudes/IA/ComputerVision/haarcascades/haarcascade_frontalface_default.xml')
#eye_cascade = cv2.CascadeClassifier('/content/drive/MyDrive/Etudes/IA/ComputerVision/haarcascades/haarcascade_eye.xml')

#directement aussi
face_cascade = cv2.CascadeClassifier(cv2.samples.findFile(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'))
eye_cascade = cv2.CascadeClassifier(cv2.samples.findFile(cv2.data.haarcascades + 'haarcascade_eye.xml'))


#
#img = cv2.imread('/content/drive/MyDrive/Etudes/IA/ComputerVision/Group-Faces.jpg')
#img = cv2.imread('Data-Face/bill.jpg')
#img = cv2.imread("/content/drive/MyDrive/Etudes/IA/ComputerVision/bill.jpg")
img = cv2.imread("/content/drive/MyDrive/Etudes/IA/ComputerVision/test_smile.jpg")
img = cv2.imread("/content/drive/MyDrive/Etudes/IA/ComputerVision/jimmy2.png")

def addvirtualmask(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    faces = detect_face(img)

    offset_x = 0
    offset_y =0

    print(faces)
    for (x,y,w,h) in faces:
      
      cv2.rectangle(img,(x,y),(x+w+offset_x,y+h+offset_y),(255,0,0),2)
      roi_gray = gray[y:y+h, x:x+w]
      roi_color = img[y:y+h, x:x+w]
      cv2.circle(roi_color, (x, h//2), 3, (255, 0, 122), -1) #point mauve
      
      alpha = 0.1
      img_height=int(h//2)
      img_width=int(w)
      print("w",img_width,"h",img_height,"img shape",img.shape)

      if(img_width>=10 and img_height>=10):  # dimension minimal pour coller la texture
        img_virtual_mask = cv2.imread("masque.png")
        resized_img = cv2.resize(img_virtual_mask, (img_width,img_height), interpolation = cv2.INTER_AREA)
        print("shape", resized_img.shape)
        dim=resized_img.shape
        Y=int(h) - 25
        X=int(x)
        y_ = -dim[0]
        print("shape ",X, Y)
        
        
        if (Y>10 and X>10):
          weighted_img = cv2.addWeighted(img[Y:Y+dim[0],X:X+dim[1],:],alpha,resized_img,1-alpha,0)
          print("shape img ",X, Y, " weighted", weighted_img.shape)
          img[Y:Y+dim[0] , X:X+dim[1] ] = weighted_img
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #plt.imshow(img)
    return img


In [39]:
# Capturing video from webcam:
cap = cv2.VideoCapture(0)

while (cap.isOpened()):

    # Capture frame-by-frame
    ret, frame = cap.read()
    frame = addvirtualmask(frame)
    cv2.imshow('frame', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):  # if 'q' is pressed then quit
        break



# When everything done, release the capture
cap.release()

cv2.destroyAllWindows()

[[ 12  52  64  64]
 [116  55  72  72]]
w 64 h 32 img shape (480, 640, 3)
shape (32, 64, 3)
shape  12 39
shape img  12 39  weighted (32, 64, 3)
w 72 h 36 img shape (480, 640, 3)
shape (36, 72, 3)
shape  116 47
shape img  116 47  weighted (36, 72, 3)
[[24 50 60 60]]
w 60 h 30 img shape (480, 640, 3)
shape (30, 60, 3)
shape  24 35
shape img  24 35  weighted (30, 60, 3)
[[353  81  45  45]
 [ 31  49  63  63]]
w 45 h 22 img shape (480, 640, 3)
shape (22, 45, 3)
shape  353 20
shape img  353 20  weighted (22, 45, 3)
w 63 h 31 img shape (480, 640, 3)
shape (31, 63, 3)
shape  31 38
shape img  31 38  weighted (31, 63, 3)
[[355  84  45  45]
 [ 37  52  61  61]]
w 45 h 22 img shape (480, 640, 3)
shape (22, 45, 3)
shape  355 20
shape img  355 20  weighted (22, 45, 3)
w 61 h 30 img shape (480, 640, 3)
shape (30, 61, 3)
shape  37 36
shape img  37 36  weighted (30, 61, 3)
[[362  86  46  46]
 [ 43  56  60  60]]
w 46 h 23 img shape (480, 640, 3)
shape (23, 46, 3)
shape  362 21
shape img  362 21  weighted 

In [ ]:
import numpy as np
import cv2
import imutils
import numpy as np

#import cv2.imshow as cv2_imshow

from matplotlib import pyplot as plt

# initialize the Haar Cascade face detection model 
face_cascade = cv2.CascadeClassifier('/content/drive/MyDrive/Etudes/IA/ComputerVision/haarcascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('/content/drive/MyDrive/Etudes/IA/ComputerVision/haarcascades/haarcascade_eye.xml')

# directement aussi
#face_cascade = cv2.CascadeClassifier(cv2.samples.findFile(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'))
#eye_cascade = cv2.CascadeClassifier(cv2.samples.findFile(cv2.data.haarcascades + 'haarcascade_eye.xml'))


#
img = cv2.imread('/content/drive/MyDrive/Etudes/IA/ComputerVision/test_smile.jpg')
#img = cv2.imread('Data-Face/bill.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray, 1.3, 5)

offset_x = 5
offset_y = 40
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w+offset_x,y+h+offset_y),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    print(eyes)
    put_imaginary_mask(eyes, roi_color, img)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
        cv2.circle(roi_color, (ex, ey), 2, (255, 0, 122), -1) #point mauve

      
plt.imshow(img)


[[ 9 19 60 60]]


TypeError: ignored

In [ ]:
def put_imaginary_mask(smiles, eye_region, img):
  offset
  for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w+offset_x,y+h+offset_y),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (sx,sy, sw,sh) in smiles:
        if(sw>0):
            print("flag1")
            #cv2.rectangle(roi_color,(sx,sy),(sx+sw,sy+sh),(0,255,0),2)
            #cv2.circle(roi_color, (sx, sy), 2, (255, 0, 122), -1) #point mauve
            factorh = 1
            factorw = 1

            img_height=int(sh*factorh)
            img_width=int(sw*factorw)
            print("w",img_width,"h",img_height,"img shape",img.shape)

            if(img_width>=0 and img_height>=10):  # dimension minimal pour coller la texture
                #        print('Original Dimensions : ',img_manche.shape)
                #"correction", "Manche" // "fin", "Manche" // "longueur", "Manche"
                #offset= cv2.getTrackbarPos("hauteur", "Manche")
                #fin=cv2.getTrackbarPos("Alignement", "Manche")
                alpha=0.1
                #rotation de l'image texture suivant l'angle du manche et redimensionnement de l'image au dimension de la boite
                #resized_img = cv2.resize(img_manche, (img_width,img_height), interpolation = cv2.INTER_AREA)
                #rotated_img=rotate_image(img_manche,angle-90)
                img_virtual_mask = cv2.imread("/content/drive/MyDrive/Etudes/IA/ComputerVision/masque.png")
                resized_img = cv2.resize(img_virtual_mask, (img_width,img_height), interpolation = cv2.INTER_AREA)
                
                #resized_img = cv2.resize(rotated_img, dim, interpolation = cv2.INTER_AREA)
                #----------------------------------------------------------------------
                #calque_height=abs(y_up_left-y_down_right)
                #calque_width=abs(x_down_right-x_up_left) 
                print("shape", resized_img.shape)
                dim=resized_img.shape
                #print("w1",abs())
                #print("dim: ", resized_img.shape)
                #alpha=0.4
                Y=int(sy+)
                X=int(sx)
                cv2.line(img, (Y, sh), (X, sx), (0, 255, 0), thickness=2)
                
                offset = 4
                #Y=y21
                # Coller la texture sur le background image/image
                weighted_img = cv2.addWeighted(img[Y:Y+dim[0],X:X+dim[1],:],alpha,resized_img,1-alpha,0)
                # add image to frame
                #print("H ",img_height>=20,"L ",img_width>=300 )
                #print("largeur: ",img_width,"H: ",img_height)
                
            
                
            
            
                img[Y:Y+dim[0] , X:X+dim[1] ] = weighted_img
                #plt.imshow(img)
            #bgrimg = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
            #cv2.imshow("hsv",bgrimg)
                        # Display the resulting frame
    return img